#!/bin/sh

for cmd in "mkdir -p files/directory"\
    "touch files/untagged.txt"\
    "touch files/ibm.txt"\
    "chtag -tc IBM-1047 files/ibm.txt"\
    "touch files/iso.txt"\
    "chtag -tc ISO8859-1 files/iso.txt"\
    "ln -sf iso.txt files/iso_link.txt"
do
    $cmd
    if [ "$?" -ne 0 ]; then
        echo "FAILURE for ${cmd}"
        exit 1
    fi
done

exit 0
